import "./style.css";
import pigeonIcon from "../../../../resources/pigeon.svg";

type Contact = { id: string; server: string };
type Message = { conversation: string; sender: string; text: string; timestamp: number };
type Conversation = { id: string; title: string; kind: "direct" | "group"; preview?: string; timestamp?: number; unread: number };
type Device = { id: string; state: "active" | "dormant" | "revoked"; last_activity?: number };
type Route = { server: string; revision: number; relay_fingerprint: string; tls_spki_fingerprint: string };
type Account = { identity?: string; server?: string; contacts: Contact[]; conversations: Conversation[]; devices: Device[]; route?: Route; messages: Message[]; state_exists: boolean };
type Api = { status(): Promise<Account>; create(server: string): Promise<void>; send(to: string, text: string): Promise<void>; groupSend(group: string, text: string): Promise<void>; importContact(card: string): Promise<void>; shareCard(): Promise<string>; markRead(conversation: string): Promise<void> };
const invoke = <T>(command: string, args?: unknown) => ((window as unknown) as Window & { __TAURI__: { core: { invoke<T>(command: string, args?: unknown): Promise<T> } } }).__TAURI__.core.invoke<T>(command, args);
const api: Api = (window as Window & { __TAURI__?: unknown }).__TAURI__
  ? { status: () => invoke("account_status"), create: server => invoke("create_identity", { server }), send: (to, text) => invoke("send_direct", { to, text }), groupSend: (group, text) => invoke("send_group", { group, text }), importContact: card => invoke("import_contact", { card }), shareCard: () => invoke("share_card"), markRead: conversation => invoke("mark_read", { conversation }) }
  : { status: async () => ({ state_exists: false, contacts: [], conversations: [], devices: [], messages: [] }), create: async () => {}, send: async () => {}, groupSend: async () => {}, importContact: async () => {}, shareCard: async () => "", markRead: async () => {} };

let account: Account;
let selected = "";
let page: "chats" | "contacts" | "devices" | "settings" = "chats";
let notice = "";
const app = document.querySelector<HTMLDivElement>("#app")!;
const esc = (value: string) => value.replace(/[&<>"]/g, char => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[char]!));
const stamp = (value?: number) => value ? new Date(value * 1000).toLocaleString([], { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }) : "";
const flash = (message: string) => { notice = message; render(); window.setTimeout(() => { notice = ""; render(); }, 3500); };
async function refresh() { account = await api.status(); render(); }
async function openConversation(id: string) { selected = id; page = "chats"; await api.markRead(id); await refresh(); }
function chatList() { return account.conversations.map(c => `<button class="conversation ${selected === c.id ? "active" : ""}" data-conversation="${c.id}"><span class="avatar ${c.kind === "group" ? "group" : ""}">${c.kind === "group" ? "#" : c.title.slice(0, 2)}</span><span class="conversation-copy"><b>${esc(c.title)}</b><small>${esc(c.preview ?? "No messages yet")}</small></span><span class="conversation-meta"><small>${stamp(c.timestamp)}</small>${c.unread ? `<em>${c.unread}</em>` : ""}</span></button>`).join("") || `<p class="empty">No conversations yet. Add a signed contact card to begin.</p>`; }
function contactsPage() { return `<section class="panel"><h1>Contacts</h1><p>Contact cards are verified by the Rust client core before they are saved.</p><form id="import-contact"><label>Paste signed contact card<textarea required name="card" placeholder="Pigeon contact card"></textarea></label><button>Import contact</button></form><button class="secondary" id="share-card">Copy my contact card</button><div class="rows">${account.contacts.map(c => `<div><b>${c.id.slice(0, 16)}</b><small>${esc(c.server)}</small></div>`).join("") || "<p class=empty>No verified contacts.</p>"}</div></section>`; }
function devicesPage() { const rows = account.devices.map(d => `<div><span class="device-state ${d.state}"></span><span><b>${d.id.slice(0, 20)}</b><small>${d.state}${d.last_activity ? ` · ${stamp(d.last_activity)}` : " · activity not yet reported by relay"}</small></span></div>`).join("") || "<p class=empty>No device roster available.</p>"; return `<section class="panel"><h1>Devices & account</h1><p>Device authorization is signed by your root identity.</p><div class="rows">${rows}</div></section>`; }
function settingsPage() { const r = account.route; return `<section class="panel"><h1>Settings</h1><div class="rows"><div><b>Current relay</b><small>${esc(r?.server ?? account.server ?? "Unavailable")}</small></div><div><b>Routing revision</b><small>${r?.revision ?? "Unavailable"}</small></div><div><b>Relay identity fingerprint</b><small class="fingerprint">${r?.relay_fingerprint ?? "Unavailable"}</small></div><div><b>TLS SPKI pin</b><small class="fingerprint">${r?.tls_spki_fingerprint ?? "Unavailable"}</small></div></div></section>`; }
function render() {
  if (!account.state_exists) { app.innerHTML = `<main class="setup"><img src="${pigeonIcon}" alt="Pigeon"><section><p class="eyebrow">WELCOME TO PIGEON</p><h1>Your identity.<br>Your conversations.</h1><p>Choose a relay you trust. Your identity and message keys stay on this device.</p><form id="setup"><label>Relay address<input required name="server" placeholder="relay.example:8443"></label><button>Create identity</button></form></section></main>`; document.querySelector<HTMLFormElement>("#setup")!.onsubmit = async event => { event.preventDefault(); try { await api.create(new FormData(event.currentTarget as HTMLFormElement).get("server") as string); await refresh(); } catch (error) { flash(String(error)); } }; return; }
  const active = account.conversations.find(c => c.id === selected);
  const messages = account.messages.filter(m => m.conversation === selected).map(m => `<article class="message ${m.sender === account.identity ? "outgoing" : ""}"><p>${esc(m.text)}</p><small>${stamp(m.timestamp)}</small></article>`).join("") || `<div class="notice">Messages are encrypted before they leave your device.</div>`;
  const body = page === "contacts" ? contactsPage() : page === "devices" ? devicesPage() : page === "settings" ? settingsPage() : `<section id="messages">${messages}</section><form id="composer" class="composer"><textarea name="text" placeholder="Message" ${selected ? "" : "disabled"}></textarea><button ${selected ? "" : "disabled"}>Send</button></form>`;
  app.innerHTML = `<div class="shell"><aside><header><img src="${pigeonIcon}" alt=""><div><b>Pigeon</b><small>${account.identity?.slice(0, 16) ?? ""}</small></div></header><nav>${(["chats", "contacts", "devices", "settings"] as const).map(item => `<button data-page="${item}" class="${page === item ? "selected" : ""}">${item === "chats" ? "Chats" : item[0].toUpperCase() + item.slice(1)}</button>`).join("")}</nav><div class="list">${page === "chats" ? chatList() : ""}</div><footer><span class="status"></span>Connected to ${esc(account.server ?? "")}</footer></aside><main class="chat"><header><button class="back">‹</button><div><b>${page === "chats" ? (active?.title ?? "Select a conversation") : page[0].toUpperCase() + page.slice(1)}</b><small>${page === "chats" ? (active ? "End-to-end encrypted" : "Choose a chat to begin") : "Account-local state"}</small></div></header>${notice ? `<p class="toast">${esc(notice)}</p>` : ""}${body}</main></div>`;
  document.querySelectorAll<HTMLButtonElement>("[data-page]").forEach(button => button.onclick = () => { page = button.dataset.page as typeof page; render(); });
  document.querySelectorAll<HTMLButtonElement>("[data-conversation]").forEach(button => button.onclick = () => void openConversation(button.dataset.conversation!));
  document.querySelector<HTMLFormElement>("#composer")?.addEventListener("submit", async event => { event.preventDefault(); const text = new FormData(event.currentTarget as HTMLFormElement).get("text") as string; if (!text.trim() || !selected) return; try { selected.startsWith("group:") ? await api.groupSend(selected.slice(6), text) : await api.send(selected, text); await refresh(); } catch (error) { flash(String(error)); } });
  document.querySelector<HTMLFormElement>("#import-contact")?.addEventListener("submit", async event => { event.preventDefault(); try { await api.importContact(new FormData(event.currentTarget as HTMLFormElement).get("card") as string); await refresh(); flash("Contact card verified and imported."); } catch (error) { flash(`Import failed: ${String(error)}`); } });
  document.querySelector<HTMLButtonElement>("#share-card")?.addEventListener("click", async () => { try { await navigator.clipboard.writeText(await api.shareCard()); flash("Signed contact card copied."); } catch (error) { flash(`Could not copy card: ${String(error)}`); } });
}
refresh().catch(error => { app.innerHTML = `<main class="error">Unable to load Pigeon: ${esc(String(error))}</main>`; });
const tauriEvents = (window as unknown as { __TAURI__?: { event?: { listen<T>(name: string, callback: (event: { payload: T }) => void): Promise<unknown> } } }).__TAURI__?.event;
void tauriEvents?.listen<Account>("pigeon://state", event => { account = event.payload; render(); });
